spring:
  datasource:
    url: jdbc:postgresql://${BASEPROJECT_DATABASE_HOST}:${TWITTER_DB_PORT}/${TWITTER_DB_NAME}
    username: ${TWITTER_DB_USERNAME}
    password: ${TWITTER_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver